import * as Yup from "yup";

export const encounterFormSchema = Yup.object({
  firstName: Yup.string().trim().required("First Name is required"),
  lastName: Yup.string().trim().required("Last Name is required"),
  location: Yup.string().trim().required("Location is required"),
  dob: Yup.string().required("Date of birth is required"),
  serviceDate: Yup.string().required("Please Provide Service Date"),
  phoneNumber: Yup.string().required("Phone number is required"),
  email: Yup.string()
    .email("Please provide valid email")
    .required("Email is required"),
  presentIllnessHistory: Yup.string(),
  medicalHistory: Yup.string(),
  medications: Yup.string(),
  allergies: Yup.string(),
  temperature: Yup.string(),
  heartRate: Yup.string(),
  repositoryRate: Yup.string(),
  sisBP: Yup.string(),
  diaBP: Yup.string(),
  oxygen: Yup.string(),
  pain: Yup.string(),
  heent: Yup.string(),
  cv: Yup.string(),
  chest: Yup.string(),
  abd: Yup.string(),
  extr: Yup.string(),
  skin: Yup.string(),
  neuro: Yup.string(),
  other: Yup.string(),
  diagnosis: Yup.string(),
  treatmentPlan: Yup.string(),
  medicationDispensed: Yup.string(),
  procedure: Yup.string(),
  followUp: Yup.string(),
});
