import * as Yup from "yup";

export const encounterFormSchema = Yup.object({
  serviceDate: Yup.string().required("Please Provide Service Date"),
  presentIllnessHistory: Yup.string(),
  medicalHistory: Yup.string(),
  medications: Yup.string(),
  allergies: Yup.string(),
  temperature: Yup.string(),
  heartRate: Yup.string(),
  repositoryRate: Yup.string(),
  sisBP: Yup.string(),
  diaBP: Yup.string(),
  oxygen: Yup.string(),
  pain: Yup.string(),
  heent: Yup.string(),
  cv: Yup.string(),
  chest: Yup.string(),
  abd: Yup.string(),
  extr: Yup.string(),
  skin: Yup.string(),
  neuro: Yup.string(),
  other: Yup.string(),
  diagnosis: Yup.string(),
  treatmentPlan: Yup.string(),
  medicationDispensed: Yup.string(),
  procedure: Yup.string(),
  followUp: Yup.string(),
});
