export const rows = [
  {
    id: "1",
    Professions: "Software Engineer",
    "Business Name": "Acme Solutions",
    Email: "info@acmesolutions.com",
    "Fax Number": "+1 555-123-4567",
    "Phone Number": "+1 555-987-6543",
    "Business Contact": "John Smith",
  },
  {
    id: "2",
    Professions: "Marketing Manager",
    "Business Name": "Bright Marketing",
    Email: "contact@brightmarketing.com",
    "Fax Number": "+1 555-234-5678",
    "Phone Number": "+1 555-876-5432",
    "Business Contact": "Emily Johnson",
  },
  {
    id: "3",
    Professions: "Accountant",
    "Business Name": "Financial Services Inc.",
    Email: "accounting@fsi.com",
    "Fax Number": "+1 555-345-6789",
    "Phone Number": "+1 555-765-4321",
    "Business Contact": "Michael Brown",
  },
  {
    id: "4",
    Professions: "Designer",
    "Business Name": "Creative Designs",
    Email: "design@creativedesigns.com",
    "Fax Number": "+1 555-456-7890",
    "Phone Number": "+1 555-654-3210",
    "Business Contact": "Sarah Lee",
  },
  {
    id: "5",
    Professions: "Sales Executive",
    "Business Name": "SalesPro",
    Email: "sales@salespro.com",
    "Fax Number": "+1 555-567-8901",
    "Phone Number": "+1 555-543-2109",
    "Business Contact": "Alex Turner",
  },
  {
    id: "6",
    Professions: "Doctor",
    "Business Name": "Health Clinic",
    Email: "appointments@healthclinic.com",
    "Fax Number": "+1 555-678-9012",
    "Phone Number": "+1 555-432-1098",
    "Business Contact": "Dr. Jennifer White",
  },
  {
    id: "7",
    Professions: "Chef",
    "Business Name": "Gourmet Bites",
    Email: "chef@gourmetbites.com",
    "Fax Number": "+1 555-789-0123",
    "Phone Number": "+1 555-321-0987",
    "Business Contact": "David Garcia",
  },
  {
    id: "8",
    Professions: "Writer",
    "Business Name": "WordCraft",
    Email: "info@wordcraftwriters.com",
    "Fax Number": "+1 555-890-1234",
    "Phone Number": "+1 555-210-9876",
    "Business Contact": "Laura Miller",
  },
  {
    id: "9",
    Professions: "Architect",
    "Business Name": "Blueprints Architects",
    Email: "contact@blueprintsarchitects.com",
    "Fax Number": "+1 555-901-2345",
    "Phone Number": "+1 555-109-8765",
    "Business Contact": "Mark Turner",
  },
  {
    id: "10",
    Professions: "Photographer",
    "Business Name": "LensCraft Studios",
    Email: "info@lenscraftstudios.com",
    "Fax Number": "+1 555-012-3456",
    "Phone Number": "+1 555-876-5432",
    "Business Contact": "Rachel Scott",
  },
];

export const columns = [
  {
    id: "1",
    label: "Professions",
  },

  {
    id: "2",
    label: "Business Name",
  },
  {
    id: "3",
    label: "Email",
  },
  {
    id: "4",
    label: "Fax Number",
  },
  {
    id: "5",
    label: "Phone Number",
  },
  {
    id: "6",
    label: "Business Contact",
  },
  {
    id: "7",
    label: "Actions",
  },
];
