export const AppRoutes = {
  LOGIN: "/login",
  FORGOTPASSWORD: "/forgot-password",
  RESETPASSWORD: "/auth/resetPassword/:token",
  DASHBOARD: "/dashboard",
  VIEW_CASE: "/dashboard/viewcase",
  VIEW_NOTES: "/dashboard/viewnotes",
  VIEW_UPLOAD: "/dashboard/viewupload",
  SEND_ORDER: "/dashboard/sendorder",
  CLOSE_CASE: "/dashboard/closecase",
  MY_PROFILE: "/myprofile",
  PROVIDER: "/provider",
  EDIT_PHYSICIAN: "/provider/editinfo",
  CREATE_PROVIDER_ACCOUNT: "/provider/createprovideraccount",
  ACCOUNT_ACCESS: "/access",
  USER_ACCESS: "/access/useraccess",
  CREATE_ROLE: "/access/createrole",
  SCHEDULING: "/provider/scheduling",
  REQUESTED_SHIFTS: "/provider/scheduling/requestedshifts",
  PROVIDER_ON_CALL: "/provider/scheduling/provideroncall",
  PROVIDER_LOCATION: "/providerlocation",
  PARTNERS: "/partners",
  ADD_BUSINESS: "/partners/addbusiness",
  UPDATE_BUSINESS: "/partners/updatebusiness",
};
