export const rows = [
  {
    id: 1,
    recipient: "Alice Johnson",
    action: "Appointment Reminder",
    roleName: "Patient",
    mobileNumber: "555-123-4567",
    createDate: "2024-03-28",
    sentDate: "2024-03-29",
    sent: "Yes",
    sentTries: 1,
    confirmationNumber: "ABC123",
  },
  {
    id: 2,
    recipient: "Bob Williams",
    action: "Prescription Refill",
    roleName: "Pharmacy",
    mobileNumber: "555-987-6543",
    createDate: "2024-03-30",
    sentDate: null,
    sent: "No",
    sentTries: 0,
    confirmationNumber: null,
  },
  {
    id: 3,
    recipient: "Carol Adams",
    action: "Lab Test Results",
    roleName: "Physician",
    mobileNumber: "555-555-5555",
    createDate: "2024-03-25",
    sentDate: "2024-03-26",
    sent: "Yes",
    sentTries: 1,
    confirmationNumber: "PQR789",
  },
  {
    id: 4,
    recipient: "David Clark",
    action: "Insurance Claim Update",
    roleName: "Billing",
    mobileNumber: "555-777-8888",
    createDate: "2024-03-29",
    sentDate: null,
    sent: "No",
    sentTries: 0,
    confirmationNumber: null,
  },
  {
    id: 5,
    recipient: "Eva Garcia",
    action: "Appointment Confirmation",
    roleName: "Patient",
    mobileNumber: "555-222-3333",
    createDate: "2024-03-31",
    sentDate: "2024-04-01",
    sent: "Yes",
    sentTries: 1,
    confirmationNumber: "LMN012",
  },
  {
    id: 6,
    recipient: "Frank Davis",
    action: "Health Survey",
    roleName: "Research Participant",
    mobileNumber: "555-444-4444",
    createDate: "2024-03-27",
    sentDate: "2024-03-28",
    sent: "Yes",
    sentTries: 1,
    confirmationNumber: "GHI678",
  },
  {
    id: 7,
    recipient: "Grace Miller",
    action: "Follow-up Appointment",
    roleName: "Patient",
    mobileNumber: "555-666-7777",
    createDate: "2024-03-26",
    sentDate: null,
    sent: "No",
    sentTries: 0,
    confirmationNumber: null,
  },
  {
    id: 8,
    recipient: "Henry White",
    action: "Wellness Program Enrollment",
    roleName: "Participant",
    mobileNumber: "555-888-9999",
    createDate: "2024-03-24",
    sentDate: "2024-03-25",
    sent: "Yes",
    sentTries: 1,
    confirmationNumber: "JKL345",
  },
  {
    id: 9,
    recipient: "Isabel Turner",
    action: "Event Registration",
    roleName: "Attendee",
    mobileNumber: "555-999-0000",
    createDate: "2024-03-23",
    sentDate: "2024-03-24",
    sent: "Yes",
    sentTries: 1,
    confirmationNumber: "DEF901",
  },
  {
    id: 10,
    recipient: "Jack Adams",
    action: "Password Reset",
    roleName: "User",
    mobileNumber: "555-000-1111",
    createDate: "2024-03-22",
    sentDate: null,
    sent: "No",
    sentTries: 0,
    confirmationNumber: null,
  },
];

export const columns = [
  {
    id: "recipient",
    label: "Recipient",
  },
  {
    id: "action",
    label: "Action",
  },
  {
    id: "roleName",
    label: "Role Name",
  },
  {
    id: "mobileNumber",
    label: "Mobile Number",
  },
  {
    id: "createDate",
    label: "Create Date",
  },
  {
    id: "sentDate",
    label: "Sent Date",
  },
  {
    id: "sent",
    label: "Sent",
  },
  {
    id: "sentTries",
    label: "Sent Tries",
  },
  {
    id: "confirmationNumber",
    label: "Confirmation Number",
  },
];
